Blog/Controllers/AuthController.cs
using Blog.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    public class AuthController : Controller
    {
        private readonly SignInManager<IdentityUser> _signInManager;

        public AuthController(SignInManager<IdentityUser> signInManager)
        {
            _signInManager = signInManager;
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            await _signInManager
                .PasswordSignInAsync(vm.UserName, vm.Password, false, false);

            return RedirectToAction("Index", "Home");
        }


        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Blog/Controllers/PanelController.cs
using Blog.Data.FileManager;
using Blog.Data.Repositories;
using Blog.Models;
using Blog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PanelController : Controller
    {
        private readonly IRepository _repository;
        private readonly IFileManager _fileManager;

        public PanelController(IRepository repository, IFileManager fileManager)
        {
            _repository = repository;
            _fileManager = fileManager;
        }


        public IActionResult Index()
        {
            var posts = _repository.GetAllPosts();

            return View(posts);
        }


        public IActionResult Edit(int? id)
        {
            if (id is null)
            {
                return View();
            }

            var post = _repository.GetPost((int) id);


            return View(new PostViewModel
            {
                Id = post.Id,
                Title = post.Title,
                Body = post.Body,
                Description = post.Description,
                Tags = post.Tags,
                Category = post.Category
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(PostViewModel vm)
        {
            var fileName = await _fileManager.SaveImage(vm.Image);

            var post = new Post
            {
                Id = vm.Id,
                Title = vm.Title,
                Body = vm.Body,
                Image = fileName,
                Description = vm.Description,
                Category = vm.Category,
                Tags = vm.Tags
            };


            if (post.Id == 0)
            {
                _repository.AddPost(post);
            }
            else
            {
                _repository.UpdatePost(post);
            }


            await _repository.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Remove(int id)
        {
            _repository.RemovePost(id);

            await _repository.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Blog/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/trumbowyg.min.css" rel="stylesheet" />
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.Keywords" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        <nav>
            <a asp-controller="Home" asp-action="Index">Index</a>
            <a asp-controller="Home" asp-action="Index" asp-route-category="programming">Programming</a>
            <a asp-controller="Home" asp-action="Index" asp-route-category="travel">Travel</a>
            <a asp-controller="Panel" asp-action="Index">Admin Panel</a>

            @if (SignInManager.IsSignedIn(User))
            {
                <a asp-controller="Auth" asp-action="Logout">Logout</a>
            }
            else
            {
                <a asp-controller="Auth" asp-action="Login">Login</a>
            }
        </nav>

    </div>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/trumbowyg.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>